#!/usr/bin/env bash
# Display "To infinity and beyond" endlessly,
# insert "sleep 2" between each iteration.
# insert "I am invincible!!!" between each iteration.

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible"' SIGTERM 
done
