#!/usr/bin/env bash
# Displays numbers from 1 to 100 in a list format, and displays
#   "FizzBuzz" when number is a multiple of 3 and 5.
#   "Fizz" when number is a multiple of 3.
#   "Buzz" when number is a multiple of 5.
#   Else, displays the number.

for num in {1..100}
do
  if (( num % 3 == 0 && num % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( num % 3 == 0 ))
  then
    echo "Fizz"
  elif (( num % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$num"
  fi
done
