#!/usr/bin/env bash
# Parses Apache log files in a list format.
#   Groups visitors by their IP and HTTP status codes.
#   Displays number of occurrences, IP, and HTTP status
#+  code of each log, in a sorted order.

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
