#!/usr/bin/env bash
# Display "Best School" 10 times by using the while loop.
#  Display "Hi" before the "Best School" on the 9th time.

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
